#!/bin/sh

# This file was generated by Simplicity Studio from the following template:
#   platform/bootloader/meta-inf/template/efr32/efr32-postbuild.sh
# Please do not edit it directly.

# Post Build processing for bootloader

# use PATH_SCMD env var to override default path for Simplicity Commander
if [ -z "${PATH_SCMD}" ]; then
  COMMANDER=$3
  case `uname` in CYGWIN*) COMMANDER="`cygpath ${COMMANDER}`";; esac
else
  COMMANDER="${PATH_SCMD}/commander"
fi

if [ ! -f "${COMMANDER}" ]; then
  echo "Error: Simplicity Commander not found at '${COMMANDER}'"
  echo "Use PATH_SCMD env var to override default path for Simplicity Commander."
  exit
fi

FILENAME=$1
BTL=$2
echo " "
echo "Add bootloader to image (${FILENAME}-with-btl.hex)"
echo " "
"${COMMANDER}" convert "${BTL}" "${FILENAME}.hex" -o "${FILENAME}-with-btl.hex"
