// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_version                         10
#define gattdb_ctrlp                           12
#define gattdb_std_auth                        15
#define gattdb_ota_ctrlp                       18
#define gattdb_ota_data                        21
#define gattdb_rx                              25
#define gattdb_tx                              27

#endif
