/***************************************************************************//**
 * @file
 * @brief BT Mesh application memory configuration
 *******************************************************************************
 * # License
 * <b>Copyright 2018 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/

/*****************************************************************************
 *  Autogenerated file, do not edit
 ****************************************************************************/

#ifndef _MESH_APP_MEMORY_CONFIG_H
#define _MESH_APP_MEMORY_CONFIG_H

#define MESH_CFG_MAX_ELEMENTS                   1
#define MESH_CFG_MAX_MODELS                     5
#define MESH_CFG_MAX_APP_BINDS                  4
#define MESH_CFG_MAX_SUBSCRIPTIONS              4
#define MESH_CFG_MAX_NETKEYS                    1
#define MESH_CFG_MAX_APPKEYS                    2
#define MESH_CFG_NET_CACHE_SIZE                 16
#define MESH_CFG_RPL_SIZE                       16
#define MESH_CFG_MAX_SEND_SEGS                  2
#define MESH_CFG_MAX_RECV_SEGS                  2
#define MESH_CFG_MAX_VAS                        1
#define MESH_CFG_MAX_PROV_SESSIONS              1
#define MESH_CFG_MAX_PROV_BEARERS               1
#define MESH_CFG_MAX_GATT_CONNECTIONS           0
#define MESH_CFG_GATT_TXQ_SIZE                  0
#define MESH_CFG_MAX_PROVISIONED_DEVICES        0
#define MESH_CFG_MAX_PROVISIONED_DEVICE_APPKEYS 0
#define MESH_CFG_MAX_PROVISIONED_DEVICE_NETKEYS 0
#define MESH_CFG_MAX_FOUNDATION_CLIENT_CMDS     0
#define MESH_CFG_MAX_FRIENDSHIPS                0
#define MESH_CFG_FRIEND_MAX_SUBS_LIST           0
#define MESH_CFG_FRIEND_MAX_TOTAL_CACHE         0
#define MESH_CFG_FRIEND_MAX_SINGLE_CACHE        0
#define MESH_CFG_MAX_APP_SEND_QUEUE             5
#define MESH_CFG_SCENE_CLIENT_MODELS            0
#define MESH_CFG_SCENE_SERVER_MODELS            0
#define MESH_CFG_LC_CLIENT_MODELS               0
#define MESH_CFG_LC_SERVER_MODELS               0

#endif
